<?php

$title = 'Registration';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
/** @var \Application\Form\RegisterForm $form */
$form->setAttribute('action', $this->url('application', ['action' => 'register']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('firstName'));
echo $this->formRow($form->get('lastName'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
